/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package nl.kinokiru.java;

import nl.kinokiru.java.models.LinkedList;

public class App {
    public static void main(String[] args) {
        LinkedList<String> owo = new LinkedList<>();

        for (int i = 0; i < 100; i++) {
            owo.add(String.format("%d", i));
        }

        System.out.println(owo.toString());
        owo.remove(54);
        System.out.println(owo.toString());
        System.out.println(owo.get(33));
        System.out.println(owo.get(-99));
    }
}
